# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: adityakumar5155
app: qr-scanner
service: qr-scanner

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: api
  environment:
    DB_URI: ${env:DB_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: app.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
    - serverless-plugin-split-stacks
    - serverless-dotenv-plugin
    - serverless-offline